# Generated by Django 2.1.7 on 2019-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineapp', '0002_categoriamodel_produtomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='descricao_produto',
            field=models.TextField(default='  ', max_length=200),
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
    ]
