# Generated by Django 2.1.7 on 2019-04-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineapp', '0005_auto_20190404_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariomodel',
            name='usuario',
        ),
    ]
